# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: unnecessary

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Make env file
      env:
        PROD_ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
      run: |
        echo $PROD_ENV_FILE | base64 --decode > .env  
    - run: npm ci    
    - run: npm run ex ${{ secrets.SERVER_HOST }}
    - run: npm run build --if-present
    - name: Deploy with rsync
      run: rsync -avz -e "ssh -i ~/.ssh/github-actions" ./dist/ root@${{ secrets.SSH_HOST }}:/var/www/cicd/
    - run: npm test 
